<a href="https://colab.research.google.com/github/EduardoArenasI/52524/blob/main/prueba_maestria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#paso 2 verificar el entorno

print ("phyton :", sys.version )
print ("pandas:", pd.__version__)

phyton : 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
pandas: 2.2.2

In [3]:
#cargar data

ds = pd.read_csv('data1.csv')

In [4]:
print(ds.head())

  ClienteID     Genero  Jubilado Socio Dependientes  Permanencia  \
0   QM-5876   Femenino         0    Si           Si           23
1   AX-2277   Femenino         0    No           No           32
2   JT-9442   Femenino         0    No           No           11
3   PH-0979  Masculino         0    Si           Si           69
4   SV-3067   Femenino         0    Si           No           68

  ServicioTelefonico MultiplesLineas ServicioInternet      SeguridadOnline  \
0                 Si              No               No  No internet service
1                 Si              No               No  No internet service
2                 Si              No               No  No internet service
3                 Si              Si      Fiber optic                   No
4                 Si              No              DSL                   Si

   ... DispositivosProtegidos       SoporteTecnico          StreamingTV  \
0  ...    No internet service  No internet service  No internet service
1  ...    No internet service  No internet service  No internet service
2  ...    No internet service  No internet service  No internet service
3  ...                     Si                   No                   Si
4  ...                     No                   Si                   No

       StreamingMovies        Contrato Facturacion              MetodoPago  \
0  No internet service        One year          No       Deposito bancario
1  No internet service        One year          No  Transferencia Bancaria
2  No internet service        One year          No      Tarjeta de Credito
3                   Si  Month-to-month          Si      Tarjeta de Credito
4                   No        One year          No  Transferencia Bancaria

  CargoMensual  CargoTotal Cancelacion
0        20.05      415.10          No
1        19.75      624.15          No
2        20.05      237.70          No
3        99.45     7007.60          Si
4        55.90     3848.80          No

[5 rows x 21 columns]

In [5]:
print(ds.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ClienteID               7043 non-null   object
 1   Genero                  7043 non-null   object
 2   Jubilado                7043 non-null   int64
 3   Socio                   7043 non-null   object
 4   Dependientes            7043 non-null   object
 5   Permanencia             7043 non-null   int64
 6   ServicioTelefonico      7043 non-null   object
 7   MultiplesLineas         7043 non-null   object
 8   ServicioInternet        7043 non-null   object
 9   SeguridadOnline         7043 non-null   object
 10  RespaldoOnline          7043 non-null   object
 11  DispositivosProtegidos  7043 non-null   object
 12  SoporteTecnico          7043 non-null   object
 13  StreamingTV             7043 non-null   object
 14  StreamingMovies         7043 non-null   object
 15  Contrato                7043 non-null   object
 16  Facturacion             7043 non-null   object
 17  MetodoPago              7043 non-null   object
 18  CargoMensual            7043 non-null   float64
 19  CargoTotal              7043 non-null   object
 20  Cancelacion             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [8]:
print(" valores nulos: ", ds.isnull().sum())

 valores nulos:  ClienteID                 0
Genero                    0
Jubilado                  0
Socio                     0
Dependientes              0
Permanencia               0
ServicioTelefonico        0
MultiplesLineas           0
ServicioInternet          0
SeguridadOnline           0
RespaldoOnline            0
DispositivosProtegidos    0
SoporteTecnico            0
StreamingTV               0
StreamingMovies           0
Contrato                  0
Facturacion               0
MetodoPago                0
CargoMensual              0
CargoTotal                0
Cancelacion               0
dtype: int64

In [10]:
ds. describe (include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ClienteID,7043,7041,CN-3721,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genero,7043,2,Masculino,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jubilado,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Socio,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependientes,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Permanencia,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
ServicioTelefonico,7043,2,Si,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultiplesLineas,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ServicioInternet,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeguridadOnline,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RespaldoOnline,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DispositivosProtegidos,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SoporteTecnico,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contrato,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Facturacion,7043,2,Si,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MetodoPago,7043,4,Cheque,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CargoMensual,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
CargoTotal,7043,6531,20.20,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cancelacion,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN